new passwords management policy -ldap
georchestra/georchestra pull request #3965
Opened 2023-05-04 22:34 UTC by marwanehcine

Steps to enable rotation password management policy

2023-05-05 06:40 UTC, fvanderbiest requested changes
Thanks for the documentation.
Minor comments to be addressed.

2023-05-05 06:40 UTC, fvanderbiest commented on docs/setup/openldap.md
> +sudo ldapadd -Y EXTERNAL -H ldapi:/// -f ppolicy-rotation.ldif
Please use triple quotes, as above, for commands.

2023-05-05 06:40 UTC, fvanderbiest commented on docs/setup/openldap.md
> +To disable password expire for no humain users (geoserver_privileged_user, idatafeeder), please run the following commands::
"To disable password expiration for internal users"
Also an extra `:` char at EOL

2023-05-05 06:40 UTC, fvanderbiest commented on docs/setup/openldap.md
> +
extra blank lines to be removed

2023-05-05 06:40 UTC, fvanderbiest commented on docs/setup/openldap.md
> +If  rotation policy for passwords management is enabled, password has to be set after 12 months.
This duration can be set with the XXX option in the XXX file.

2024-01-11 10:33 UTC, pmauduit approved these changes

2024-01-11 10:34 UTC, merged