Making rabbitmq dependency optional on console
georchestra/georchestra pull request #4047
Opened 2023-10-04 23:05 UTC by marwanehcine

On this PR, we make  rabbitmq dependency optional on console

2023-10-05 07:22 UTC, pmauduit reviewed
Thanks Marwanne, it indeed looks more relevant than the previous one without mixing spring-boot components.

I am wondering what a ApplicationContextInitializer provides though, why not just sourcing the /etc/georchestra/default.properties directly from the xml file ?

2023-10-05 09:17 UTC, marwanehcine commented
> Thanks Marwanne, it indeed looks more relevant than the previous one without mixing spring-boot components.
> 
> I am wondering what a ApplicationContextInitializer provides though, why not just sourcing the /etc/georchestra/default.properties directly from the xml file ?

The problem here is that <import>  in xml conf file for spring 3 are called before reading props file, so the only solution is to define listerner on web.xml to source default.props before <import>.  this is the only way it works!

2023-10-05 10:02 UTC, marwanehcine commented on console/src/main/webapp/WEB-INF/web.xml
> +    </context-param>
Hello, good question, issue here is that "<import>" inside xml conf file (beans definition) is called too early so props files a not accessible yet, however using context-param, we load default.properties file even before call to <import> on this case.
I have checked other cases and it did not work only after user of context-param inside web.xml file

2023-10-05 10:02 UTC, marwanehcine commented on console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
> +  <import resource="classpath:spring/rabbit-context-${enableRabbitmqEvents}.xml"/>
code updated

2023-10-05 10:03 UTC, marwanehcine commented on console/src/main/java/org/georchestra/console/events/DefaultPropsInitializer.java
> +                    new ResourcePropertySource(new FileSystemResource("/etc/georchestra/default.properties")));
code updated!

2023-10-05 10:37 UTC, pmauduit commented on console/src/main/java/org/georchestra/console/events/DefaultPropsInitializer.java
> +            LOGGER.error(e.getStackTrace());
maybe LOGGER.error for the first one as well ?

2023-10-05 10:58 UTC, pmauduit commented on console/src/main/java/org/georchestra/console/events/DefaultPropsInitializer.java
> +            LOGGER.error(e.getStackTrace());
or even `LOGGER.error("Cannot find ...", e);`

2023-10-12 07:24 UTC, pmauduit requested changes

2023-10-12 07:24 UTC, pmauduit commented on console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
> +  <import resource="classpath:spring/rabbit-context-${enableRabbitmqEvents:true}.xml"/>
false by default ?

2023-10-12 07:49 UTC, marwanehcine commented on console/src/main/webapp/WEB-INF/spring/webmvc-config.xml
> +  <import resource="classpath:spring/rabbit-context-${enableRabbitmqEvents:true}.xml"/>
done.

2023-10-12 08:06 UTC, pmauduit commented on console/src/main/java/org/georchestra/console/events/DefaultPropsInitializer.java
> +            LOGGER.error(e.getStackTrace());
you can still put the exception as argument from the Logger.error call I'd expect.

2023-10-24 08:36 UTC, merged